### ISSUE TITLE
XPosed Log full of errors (NullPointerException)

### ISSUE THREAD

**Issue by francwalter** [qwerty12/AlternateAppPicker#3]
Hello

I use Alternate App Picker Xposed module 1.02 beta on my Samsung Galaxy S2 with OS 4.1.2 (Goatrip v7.0 ROM).
The module works, but when I look into the log of XPosed I see many errors:

...
Loading modules from /data/app/com.mohammadag.disablecleardefaultsdialog-1.apk
  Loading class com.mohammadag.disablecleardefaultsdialog.DisableClearDefaultsDialog
java.lang.NullPointerException
    at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:561)
    at com.android.internal.app.ResolverActivity.onCreate(Native Method)
    at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5206)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:561)
    at com.android.internal.app.ResolverActivity.onCreate(Native Method)
    at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5206)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:561)
    at com.android.internal.app.ResolverActivity.onCreate(Native Method)
    at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5206)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:561)
    at com.android.internal.app.ResolverActivity.onCreate(Native Method)
    at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5206)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:561)
    at com.android.internal.app.ResolverActivity.onCreate(Native Method)
    at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5206)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:561)
    at com.android.internal.app.ResolverActivity.onCreate(Native Method)
    at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5206)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at pk.qwerty12.alternateapppicker.AlternateAppPicker$1.afterHookedMethod(AlternateAppPicker.java:68)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:561)
    at com.android.internal.app.ResolverActivity.onCreate(Native Method)
    at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5206)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
    at dalvik.system.NativeStart.main(Native Method)

Is there anything I can do to get rid of these errors?

Thanks 
frank

**Comment by francwalter** [comment]
Is there any further bugfix or development in this module or is it abandoned?
I still have these many errors on now Xposed 2.6.1 on my SGS2 with CM 10.2.1 so now I disable it, might be too buggy.

**Comment by qwerty12** [comment]
Sorry, yes - I never even use any of my modules. Have you looked at p.valenta's Complete Action Plus? I think it can do everything this can do and more.
